services:
  - type: web
    name: spirit-ai-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: mongodb+srv://MythDB:Rohit%40123@mythai.lc5iznd.mongodb.net/?appName=MythAi
      - key: DB_NAME
        value: mythai
      - key: USE_FAISS
        value: false
      - key: VECTOR_DIM
        value: 384
      - key: QDRANT_URL
        value: https://0f6ebc58-11de-4e49-aeb7-b465c18b943e.europe-west3-0.gcp.cloud.qdrant.io
      - key: QDRANT_API_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.XDYdIhRYv9HXJ99yosgPg7IQ3DJSsjWjUEZI6CleF6w
      - key: QDRANT_COLLECTION
        value: myth_texts_384
      - key: OPEN_ROUTER_API_KEY
        value: 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
      - key: OPEN_ROUTER_CHAT_MODEL
        value: meta-llama/llama-3.2-3b-instruct:free
      - key: RETRIEVE_TOP_K
        value: 4
      - key: CHUNK_SIZE_CHARS
        value: 1200
      - key: CHUNK_OVERLAP_CHARS
        value: 150
      - key: ELEVENLABS_API_KEY
        value: sk_a3b53f751a92e407a0f3a2d2ba59b95360015503f3364603
      - key: ELEVENLABS_VOICE_ID
        value: JBFqnCBsd6RMkjVY5Cd5
      - key: TTS_PROVIDER
        value: elevenlabs
      - key: SARVAM_API_KEY
        value: sk_kvj5rcn0_8mcaWzkSIn5yclkaLGSppiyY
      - key: GEMINI_API_KEY
        value: AIzaSyDESeACmzUYK2TCTwEIJhn-BfITBhNs9qM
      - key: SUPABASE_URL
        value: https://ttpjmshzcicgvjhzkzfs.supabase.co
      - key: SUPABASE_ANON_KEY
        value: sb_publishable_MMxMEAhYpZPj0SPcw6A1rA_5tBBKDV9
      - key: RESEND_API_KEY
        value: re_MPCYHh42_DktcwbLwEnMrGeUfpTviKarn
      - key: EMAIL_USER
        value: spirit.ai.temp@gmail.com
      - key: EMAIL_APP_PASSWORD
        value: 0u}j;4g48yahIyK
      - key: EMAIL_FROM
        value: spirit.ai.temp@gmail.com
      - key: EMAIL_FROM_NAME
        value: Spirit AI
      - key: JWT_SECRET
        value: mythai-super-secret-jwt-key-change-in-production-2024
      - key: USE_INTENT_LAYER
        value: true
      - key: LLM_PROVIDER
        value: openrouter
      - key: USE_MCP
        value: false
      - key: ENABLE_ENHANCED_CONVERSATION
        value: true
      - key: STRICT_RAG_GROUNDING
        value: true
      - key: FRONTEND_URL
        value: https://spirit-ai-psi.vercel.app